services:

  nginxYahya:
    image: ubuntu/nginx
    container_name: yahya_server
    volumes:
      - ./nginx/yahya/sites-available:/etc/nginx/sites-available
      - ./nginx/yahya/website:/var/www/html/
    restart: always
    networks:
      - proxyinverso

  nginxElhadri:
    image: ubuntu/nginx
    container_name: elhadri_server
    volumes:
      - ./nginx/elhadri/sites-available:/etc/nginx/sites-available
      - ./nginx/elhadri/website:/var/www/html/
    restart: always
    networks:
      - proxyinverso    

  apache:
    image: ubuntu/apache2
    container_name: seguro_server
    volumes:
      - ./apache/sites-available:/etc/apache2/sites-available
      - ./apache/website:/var/www/html/
      - ./apache/htpasswd/.htpasswd:/etc/apache2/.htpasswd
    restart: always
    networks:
      - proxyinverso

  proxy:
    image: ubuntu/nginx
    container_name: proxy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    restart: always
    depends_on:
      - apache
      - nginxYahya
      - nginxElhadri
    networks:
      - proxyinverso

networks:
  proxyinverso:
